-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 20:23:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_polo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_polo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_polo` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_polo` ;

-- -----------------------------------------------------
-- Table `proyecto_polo`.`tipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`tipoDocumento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoDocumento` INT NOT NULL,
  `numeroDocumento` BIGINT NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` BIGINT NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `rol` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipoDocumento_idx` (`tipoDocumento` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `numeroDocumento_UNIQUE` (`numeroDocumento` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  INDEX `fk_usuario_rol1_idx` (`rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipoDocumento`
    FOREIGN KEY (`tipoDocumento`)
    REFERENCES `proyecto_polo`.`tipoDocumento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `proyecto_polo`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profesor_usuario1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `proyecto_polo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`institucion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_de_institucion` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `ciudad` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `institucion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_administrador_usuario1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_administrador_institucion1_idx` (`institucion` ASC) VISIBLE,
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `proyecto_polo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administrador_institucion1`
    FOREIGN KEY (`institucion`)
    REFERENCES `proyecto_polo`.`institucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`grado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `directorGrupo` INT NOT NULL,
  `institucion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grado_profesor1_idx` (`directorGrupo` ASC) VISIBLE,
  INDEX `fk_grado_institucion1_idx` (`institucion` ASC) VISIBLE,
  CONSTRAINT `fk_grado_profesor1`
    FOREIGN KEY (`directorGrupo`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grado_institucion1`
    FOREIGN KEY (`institucion`)
    REFERENCES `proyecto_polo`.`institucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`estudiante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `grado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiante_usuario1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_estudiante_grado1_idx` (`grado` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `proyecto_polo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_grado1`
    FOREIGN KEY (`grado`)
    REFERENCES `proyecto_polo`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`asignatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `profesor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materia_profesor1_idx` (`profesor` ASC) VISIBLE,
  CONSTRAINT `fk_materia_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`tipoArchivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`tipoArchivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`tipoActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`tipoActividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profesor` INT NOT NULL,
  `asignatura` INT NOT NULL,
  `estudiante` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `estado` ENUM('pendiente', 'completada', 'vencida') NOT NULL,
  `tipoArchivo_id` INT NOT NULL,
  `tipoActividad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarea_profesor1_idx` (`profesor` ASC) VISIBLE,
  INDEX `fk_tarea_materia1_idx` (`asignatura` ASC) VISIBLE,
  INDEX `fk_tarea_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  INDEX `fk_actividad_tipoArchivo1_idx` (`tipoArchivo_id` ASC) VISIBLE,
  INDEX `fk_actividad_tipoActividad1_idx` (`tipoActividad_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_materia1`
    FOREIGN KEY (`asignatura`)
    REFERENCES `proyecto_polo`.`asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_tipoArchivo1`
    FOREIGN KEY (`tipoArchivo_id`)
    REFERENCES `proyecto_polo`.`tipoArchivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_tipoActividad1`
    FOREIGN KEY (`tipoActividad_id`)
    REFERENCES `proyecto_polo`.`tipoActividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`notificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `estado` ENUM('leído', 'no leída') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`grado_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`grado_materia` (
  `materia_id` INT NOT NULL,
  `grado_id` INT NOT NULL,
  PRIMARY KEY (`materia_id`, `grado_id`),
  INDEX `fk_materia_has_grado_grado1_idx` (`grado_id` ASC) VISIBLE,
  INDEX `fk_materia_has_grado_materia1_idx` (`materia_id` ASC) VISIBLE,
  CONSTRAINT `fk_materia_has_grado_materia1`
    FOREIGN KEY (`materia_id`)
    REFERENCES `proyecto_polo`.`asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_has_grado_grado1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `proyecto_polo`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`grado_tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`grado_tarea` (
  `tarea_id` INT NOT NULL,
  `grado_id` INT NOT NULL,
  PRIMARY KEY (`tarea_id`, `grado_id`),
  INDEX `fk_tarea_has_grado_grado1_idx` (`grado_id` ASC) VISIBLE,
  INDEX `fk_tarea_has_grado_tarea1_idx` (`tarea_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_has_grado_tarea1`
    FOREIGN KEY (`tarea_id`)
    REFERENCES `proyecto_polo`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_has_grado_grado1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `proyecto_polo`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`calificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actividad` INT NOT NULL,
  `estudiante` INT NOT NULL,
  `nota` FLOAT NOT NULL,
  `fechaNota` DATE NOT NULL,
  `comentarios` TEXT NOT NULL,
  `asignatura` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notas_tarea1_idx` (`actividad` ASC) VISIBLE,
  INDEX `fk_notas_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  INDEX `fk_notas_materia1_idx` (`asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_notas_tarea1`
    FOREIGN KEY (`actividad`)
    REFERENCES `proyecto_polo`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_materia1`
    FOREIGN KEY (`asignatura`)
    REFERENCES `proyecto_polo`.`asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`logro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`logro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante` INT NOT NULL,
  `profesor` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaLogro` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_logro_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  INDEX `fk_logro_profesor1_idx` (`profesor` ASC) VISIBLE,
  CONSTRAINT `fk_logro_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logro_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`notasPeriodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`notasPeriodo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notas` INT NOT NULL,
  `logro` INT NOT NULL,
  INDEX `fk_notasPeriodo_notas1_idx` (`notas` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_notasPeriodo_logro1_idx` (`logro` ASC) VISIBLE,
  CONSTRAINT `fk_notasPeriodo_notas1`
    FOREIGN KEY (`notas`)
    REFERENCES `proyecto_polo`.`calificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notasPeriodo_logro1`
    FOREIGN KEY (`logro`)
    REFERENCES `proyecto_polo`.`logro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`asistencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profesor` INT NOT NULL,
  `estudiante` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` ENUM('presente', 'ausente', 'tarde') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asistencias_profesor1_idx` (`profesor` ASC) VISIBLE,
  INDEX `fk_asistencias_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_asistencias_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistencias_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`observadorEstudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`observadorEstudiante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante` INT NOT NULL,
  `profesor` INT NOT NULL,
  `fechaObservacion` DATE NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_observadorEstudiante_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  INDEX `fk_observadorEstudiante_profesor1_idx` (`profesor` ASC) VISIBLE,
  CONSTRAINT `fk_observadorEstudiante_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observadorEstudiante_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`notificaciones_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`notificaciones_has_usuario` (
  `notificaciones_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`notificaciones_id`, `usuario_id`),
  INDEX `fk_notificaciones_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_notificaciones_has_usuario_notificaciones1_idx` (`notificaciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_notificaciones_has_usuario_notificaciones1`
    FOREIGN KEY (`notificaciones_id`)
    REFERENCES `proyecto_polo`.`notificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificaciones_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `proyecto_polo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 20:23:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_polo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_polo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_polo` DEFAULT CHARACTER SET utf8 ;
USE `proyecto_polo` ;

-- -----------------------------------------------------
-- Table `proyecto_polo`.`tipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`tipoDocumento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipoDocumento` INT NOT NULL,
  `numeroDocumento` BIGINT NOT NULL,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` BIGINT NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `rol` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipoDocumento_idx` (`tipoDocumento` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `numeroDocumento_UNIQUE` (`numeroDocumento` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  INDEX `fk_usuario_rol1_idx` (`rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipoDocumento`
    FOREIGN KEY (`tipoDocumento`)
    REFERENCES `proyecto_polo`.`tipoDocumento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `proyecto_polo`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profesor_usuario1_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `proyecto_polo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`institucion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_de_institucion` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `ciudad` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `institucion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_administrador_usuario1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_administrador_institucion1_idx` (`institucion` ASC) VISIBLE,
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `proyecto_polo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administrador_institucion1`
    FOREIGN KEY (`institucion`)
    REFERENCES `proyecto_polo`.`institucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`grado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `directorGrupo` INT NOT NULL,
  `institucion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grado_profesor1_idx` (`directorGrupo` ASC) VISIBLE,
  INDEX `fk_grado_institucion1_idx` (`institucion` ASC) VISIBLE,
  CONSTRAINT `fk_grado_profesor1`
    FOREIGN KEY (`directorGrupo`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grado_institucion1`
    FOREIGN KEY (`institucion`)
    REFERENCES `proyecto_polo`.`institucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`estudiante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `grado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiante_usuario1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_estudiante_grado1_idx` (`grado` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `proyecto_polo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_grado1`
    FOREIGN KEY (`grado`)
    REFERENCES `proyecto_polo`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`asignatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `profesor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materia_profesor1_idx` (`profesor` ASC) VISIBLE,
  CONSTRAINT `fk_materia_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`tipoArchivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`tipoArchivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`tipoActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`tipoActividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profesor` INT NOT NULL,
  `asignatura` INT NOT NULL,
  `estudiante` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `estado` ENUM('pendiente', 'completada', 'vencida') NOT NULL,
  `tipoArchivo_id` INT NOT NULL,
  `tipoActividad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarea_profesor1_idx` (`profesor` ASC) VISIBLE,
  INDEX `fk_tarea_materia1_idx` (`asignatura` ASC) VISIBLE,
  INDEX `fk_tarea_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  INDEX `fk_actividad_tipoArchivo1_idx` (`tipoArchivo_id` ASC) VISIBLE,
  INDEX `fk_actividad_tipoActividad1_idx` (`tipoActividad_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_materia1`
    FOREIGN KEY (`asignatura`)
    REFERENCES `proyecto_polo`.`asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_tipoArchivo1`
    FOREIGN KEY (`tipoArchivo_id`)
    REFERENCES `proyecto_polo`.`tipoArchivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_tipoActividad1`
    FOREIGN KEY (`tipoActividad_id`)
    REFERENCES `proyecto_polo`.`tipoActividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`notificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NOT NULL,
  `estado` ENUM('leído', 'no leída') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`grado_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`grado_materia` (
  `materia_id` INT NOT NULL,
  `grado_id` INT NOT NULL,
  PRIMARY KEY (`materia_id`, `grado_id`),
  INDEX `fk_materia_has_grado_grado1_idx` (`grado_id` ASC) VISIBLE,
  INDEX `fk_materia_has_grado_materia1_idx` (`materia_id` ASC) VISIBLE,
  CONSTRAINT `fk_materia_has_grado_materia1`
    FOREIGN KEY (`materia_id`)
    REFERENCES `proyecto_polo`.`asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_has_grado_grado1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `proyecto_polo`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`grado_tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`grado_tarea` (
  `tarea_id` INT NOT NULL,
  `grado_id` INT NOT NULL,
  PRIMARY KEY (`tarea_id`, `grado_id`),
  INDEX `fk_tarea_has_grado_grado1_idx` (`grado_id` ASC) VISIBLE,
  INDEX `fk_tarea_has_grado_tarea1_idx` (`tarea_id` ASC) VISIBLE,
  CONSTRAINT `fk_tarea_has_grado_tarea1`
    FOREIGN KEY (`tarea_id`)
    REFERENCES `proyecto_polo`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_has_grado_grado1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `proyecto_polo`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`calificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actividad` INT NOT NULL,
  `estudiante` INT NOT NULL,
  `nota` FLOAT NOT NULL,
  `fechaNota` DATE NOT NULL,
  `comentarios` TEXT NOT NULL,
  `asignatura` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notas_tarea1_idx` (`actividad` ASC) VISIBLE,
  INDEX `fk_notas_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  INDEX `fk_notas_materia1_idx` (`asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_notas_tarea1`
    FOREIGN KEY (`actividad`)
    REFERENCES `proyecto_polo`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notas_materia1`
    FOREIGN KEY (`asignatura`)
    REFERENCES `proyecto_polo`.`asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`logro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`logro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante` INT NOT NULL,
  `profesor` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fechaLogro` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_logro_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  INDEX `fk_logro_profesor1_idx` (`profesor` ASC) VISIBLE,
  CONSTRAINT `fk_logro_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logro_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`notasPeriodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`notasPeriodo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notas` INT NOT NULL,
  `logro` INT NOT NULL,
  INDEX `fk_notasPeriodo_notas1_idx` (`notas` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_notasPeriodo_logro1_idx` (`logro` ASC) VISIBLE,
  CONSTRAINT `fk_notasPeriodo_notas1`
    FOREIGN KEY (`notas`)
    REFERENCES `proyecto_polo`.`calificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notasPeriodo_logro1`
    FOREIGN KEY (`logro`)
    REFERENCES `proyecto_polo`.`logro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`asistencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profesor` INT NOT NULL,
  `estudiante` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` ENUM('presente', 'ausente', 'tarde') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asistencias_profesor1_idx` (`profesor` ASC) VISIBLE,
  INDEX `fk_asistencias_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_asistencias_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistencias_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`observadorEstudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`observadorEstudiante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estudiante` INT NOT NULL,
  `profesor` INT NOT NULL,
  `fechaObservacion` DATE NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_observadorEstudiante_estudiante1_idx` (`estudiante` ASC) VISIBLE,
  INDEX `fk_observadorEstudiante_profesor1_idx` (`profesor` ASC) VISIBLE,
  CONSTRAINT `fk_observadorEstudiante_estudiante1`
    FOREIGN KEY (`estudiante`)
    REFERENCES `proyecto_polo`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observadorEstudiante_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `proyecto_polo`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_polo`.`notificaciones_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_polo`.`notificaciones_has_usuario` (
  `notificaciones_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`notificaciones_id`, `usuario_id`),
  INDEX `fk_notificaciones_has_usuario_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_notificaciones_has_usuario_notificaciones1_idx` (`notificaciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_notificaciones_has_usuario_notificaciones1`
    FOREIGN KEY (`notificaciones_id`)
    REFERENCES `proyecto_polo`.`notificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificaciones_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `proyecto_polo`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
